#! /bin/bash
#
# A script to automatically modify the "PATCH_LEVEL" in the version file when we commit. The patch level is
# incremented by one. 
#
# This file needs to be placed manually into the ".git/hooks/" directory.
# 

echo "Set patch level"

# Version file path
VERSION_FILE="../../VCPU32-Simulator/VCPU32-Version.h"

# update the patch level
python ../../gitHooks/update-patch-level.py $VERSION_FILE

# stage the modified version file
git add "$VERSION_FILE"

# exit for git to proceed
exit 0  