#! /bin/bash
#
# A script to automatically modify the "PATCH_LEVEL" in the version file when we commit. The patch level is
# incremented by one. 
#
# This file needs to be placed manually into the ".git/hooks/" directory.
# 

echo "Set patch level"

# update the patch level
python update-patch-level.py ../VCPU32-Simulator/VCPU32-Version.h

# stage the modified version file
git add "$VERSION_FILE"

# exit for git to proceed
exit 0  